project:
  type: default
  output-dir: _output

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    embed-resources: true
    css: _style.css
    theme: cosmo

execute:
  echo: true
  warning: false
  message: false
  freeze: false
